[#263] - Eliminar redundancia de estilos
rolivencia/cuentoneta pull request #308
Opened 2023-06-18 17:30 UTC by SoyDiego

Eliminado redundancia de estilos agregando una clase wrapper en styles.scss.
Si prefieren que sea con otro nombre la clase, o crearlo en un componente, avisenme y lo modifico.

2023-06-19 02:55 UTC, ErikGIovani approved these changes
Dejo aprobado, nice work 👍

2023-06-19 20:56 UTC, rolivencia reviewed
Dado que este tipo de estilos se va a utilizar para algunas nuevas páginas en desarrollos futuros, creo que el approach no es el ideal.

El nombre de la clase elegida es demasiado general para el problema y, tal vez, para este caso deberíamos tener un componente particular que ayude a proyectar contenido estilizado de una manera determinada.

No cierro el PR pues podemos ir diseñando luego de qué manera generamos un diseño que se pueda reutilizar con facilidad y use nombres descriptivos.

2023-06-21 02:19 UTC, rolivencia commented
Diego, ¿te parece que exprese mejor el scope y forma de encarar del issue [#308] y procedemos después a ver el tema en detalle para armar el componente wrapper del que hablamos por chat? Creo que va a ser la mejor forma de proceder.

2023-06-21 02:20 UTC, rolivencia requested changes
Diego, ¿te parece que exprese mejor el scope y forma de encarar del issue [#308] y procedemos después a ver el tema en detalle para armar el componente wrapper del que hablamos por chat? Creo que va a ser la mejor forma de proceder.

2023-06-21 14:43 UTC, closed without merging