Rever colaboradores para release 2.0.3
rolivencia/cuentoneta pull request #309
Opened 2023-06-19 01:03 UTC by JimerSamuel

Agregados los nuevos colaboradores (Yo incluido) y agregados los autores de las historias.

Como sugerencia para una proxima vercion seria la de agregar un menu para ir desplegando los autores, ya que en cierto punto van a ser muchos, por ejemplo desplegar un menu para poder los autores en ingles, otro para los autores de Otoño y asi.😊

2023-06-19 02:49 UTC, ErikGIovani requested changes
Excelente 👍, solo unas pequeñas observaciones,  Juan Rodriguez aún no ha hecho ningún pull request.

También creo en los autores solo era agregar a los nuevos colaboradores de contenido, no a todos los escritores.

También te recomiendo que para próximos commits, uses la convención que venimos usando, que es agregar entre corchetes un hastag seguido del número del issue, por ejemplo `[#301] - Aquí el comentario del commit`

Fuera de eso, muy bien hecho 🥳

2023-06-19 06:06 UTC, SoyDiego commented on src/app/pages/about/about.component.html
> +          Diego Franchina (<a [href]="'https://github.com/jitrodriguez'"
Aquí hay un error, mi github es https://github.com/SoyDiego y en el usuario habría que cambiarlo a @SoyDiego.

2023-06-19 17:49 UTC, SoyDiego commented on src/app/pages/about/about.component.html
> +          Diego Franchina (<a [href]="' https://github.com/SoyDiego'"
Buenísimo el cambio 💯 , te quedó un espacio antes de https solamente @JimerSamuel .
(No se si es estas cosas se tienen en cuenta, pero por las dudas dejo el comentario, sino ya lo quitaré yo cuando haga otro PR).
Gracias!!

2023-06-19 18:11 UTC, JimerSamuel commented on src/app/pages/about/about.component.html
> +          Diego Franchina (<a [href]="' https://github.com/SoyDiego'"
Solucionado el tema del link, en efecto ese espacio no lo dejaba caer en ningún lugar.

2023-06-19 20:48 UTC, rolivencia requested changes
En el caso de los colaboradores que listamos, sólo mencionamos a aquellas personas que hayan tenido algún aporte para con el proyecto en particular.

En lo que respecta a las obras, todas ellas han sido tomadas de otros lugares de la web, por lo que no tiene sentido listar como colaboradores a estos autores.

2023-06-21 02:13 UTC, rolivencia approved these changes
Aprobado 🤝. Agrego [#318] para automatizar corridas de linter-fix y Prettier para evitar discordancias en el uso de los line breaks y espacios.

2023-06-21 02:18 UTC, merged