Cambiar la tag h3  componente header por h1
rolivencia/cuentoneta pull request #312
Opened 2023-06-20 17:07 UTC by wilago

Se relaiza el cambio como se muestra en la siguiente imagen.

![image](https://github.com/rolivencia/cuentoneta/assets/27816405/9f65a270-b638-44d3-8e1d-ac5037309184)

2023-06-20 17:14 UTC, ErikGIovani requested changes
Excelente 👍, solo faltan cambiar los estilos para que se siga viendo el h1 como el h3 y ver en que otro lugar hay otros  h1 para ver si el cambio de estilos les afecta

2023-06-20 18:33 UTC, ErikGIovani commented
> ¿Cuál es el issue relacionado a esta PR? ¿Existe uno?

Es uno de los de el issues de accesibilidad https://github.com/rolivencia/cuentoneta/issues/243

2023-06-21 01:54 UTC, rolivencia commented
Estilos originales:
![image](https://github.com/rolivencia/cuentoneta/assets/32349705/8a54c861-c347-4881-92db-8ea8624e61d8)

Estilos nuevos:
![image](https://github.com/rolivencia/cuentoneta/assets/32349705/108785d2-3aa2-4a76-b0d2-9cf0f1b75c6f)

En este caso, más allá de cambiar el tag —usar un `h3` es un error de arrastre que debe ser corregido—, también debe de respetarse el estilo que proviene del spec de Figma. Espero a por los cambios antes de aceptar y dar merge a este PR.

2023-06-21 01:56 UTC, rolivencia requested changes
Estilos originales:
![image](https://github.com/rolivencia/cuentoneta/assets/32349705/8a54c861-c347-4881-92db-8ea8624e61d8)

Estilos nuevos:
![image](https://github.com/rolivencia/cuentoneta/assets/32349705/108785d2-3aa2-4a76-b0d2-9cf0f1b75c6f)

En este caso, más allá de cambiar el tag —usar un `h3` es un error de arrastre que debe ser corregido—, también debe de respetarse el estilo que proviene del spec de Figma. Espero a por los cambios en el tamaño de fuente antes de aceptar y dar merge a este PR.

Como parte de los cambios también se puede dejar de lado el uso del tag `<strong>` como aplicado al texto.

2023-06-21 01:57 UTC, rolivencia commented
Agrego como prefijo el "[#243] -" al nombre del PR.

2023-06-21 04:04 UTC, wilago commented
Hola @rolivencia, lo que logro entender con la aclaracion que me das es que debo poner las propiedades de la etiqueta de H1 como estan estipulas en el figma  
![image](https://github.com/rolivencia/cuentoneta/assets/27816405/23fb2cb0-4bfa-4150-9c99-c443ff053603)

Es decir que dentro de 
![image](https://github.com/rolivencia/cuentoneta/assets/27816405/890ba419-b21e-460b-8277-3dd027db4cb7)

poner 
  h1{
      font-family: 'Inter';
      font-style: normal;
      font-weight: 700;
      font-size: 18px;
      line-height: 22px;
  }

2023-06-21 10:19 UTC, rolivencia commented
Así es, pero no deben usarse esos valores estáticos sino que existen tamaños y grosores determinados de tipografía disponibles en `theme.scss` para especificar el valor de esas propiedades.

2023-06-28 04:43 UTC, closed without merging