[#243][312]-Se realizan los cambios en theme.scss y en el componente header
rolivencia/cuentoneta pull request #343
Opened 2023-06-28 05:04 UTC by wilago

![image](https://github.com/rolivencia/cuentoneta/assets/27816405/4cbc3fcf-d09d-4109-b549-9b2e8819197b)

@rolivencia  estos fueron los cambios que me indicaste que realizara

![image](https://github.com/rolivencia/cuentoneta/assets/27816405/3863e82f-5965-4ed3-9920-2f0e3c334850)

Quedo atento.

2023-06-29 12:54 UTC, rolivencia requested changes

2023-06-29 12:54 UTC, rolivencia commented on src/assets/scss/theme.scss
> +    font-size: 18px;
El cambio de estilos no debe estar en `theme.scss`, sino sólo afectar al header. El lugar correcto para incluir estos estilos es `header.component.scss`

2023-06-29 17:14 UTC, wilago commented on src/assets/scss/theme.scss
> +    font-size: 18px;
Hola @rolivencia dentro del header.component.scss ya se encuentra importado el theme.scss a traves @import 'src/assets/scss/theme.scss'  y siguiendo lo que me indicas quedaria de la siguiente forma:
![image](https://github.com/rolivencia/cuentoneta/assets/27816405/134aa2d3-7f11-4288-9d3c-6cf6bd954c58)

Que pena tanta molestia, estoy un poco oxidado :( quedo atento a tu respuesta para realizar el push nuevamente.

2023-06-30 16:32 UTC, rolivencia approved these changes
Aprobado 🤝 . Buen trabajo @wilago.

2023-06-30 16:32 UTC, merged